version: '3.7'

services:

  wordpress:
    build: .
    restart: always
    ports:
      - 5000:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./wp-app:/var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php.conf.ini
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data: {}